name: Build MacOS

on:
  push:
    tags:        
      - build.*

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "flutter/devtools"
          ref: "v2.16.0"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0-0.0.pre"
          channel: "master"
      - run: flutter config --enable-macos-desktop
      - name: Build
        working-directory: ./packages/devtools_app
        run: "flutter build macos"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: macos-release
          path: ./build/macos/Build/Products/Release/devtools_app.app
