name: Test

on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello > artifact1.txt
      - uses: actions/upload-artifact@v3
        with:
          name: first
          path: artifact1.txt
  second:
    runs-on: ubuntu-latest
    steps:
      - run: echo world > artifact2.txt
      - uses: actions/upload-artifact@v3
        with:
          name: second
          path: artifact2.txt
  upload:
    runs-on: ubuntu-latest
    needs: [first, second]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: first
      - uses: actions/download-artifact@master
        with:
          name: second
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            - first
            - second


          
