name: Test

on:
  push:
    tags:
      - test.*

jobs:
  first:
    runs-on: windows-latest
    steps:
      - run: mkdir folder
      - run: echo hello > ./folder/artifact1.txt
      - run: echo hello > ./folder/artifact2.txt
      - run: tar.exe -a -c -C ./folder -f win.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: first
          path: win.zip
  second:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir folder
      - run: echo world > ./folder/artifact1.txt
      - run: echo world > ./folder/artifact2.txt
      - run: tar -cvzf second.tar.gz -C folder .
      - run: zip -r third.zip -C folder .
      - uses: actions/upload-artifact@v3
        with:
          name: second
          path: second.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: third
          path: third.zip
  upload:
    runs-on: ubuntu-latest
    needs: [first, second]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: first
      - uses: actions/download-artifact@master
        with:
          name: second
      - uses: actions/download-artifact@master
        with:
          name: third
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./second.tar.gz
            ./win.zip
            ./third.zip


          
